blog/urls.py
from django.urls import path
from blog.views import (
    PostView, PostsView, CategoryView,
    AddPostView, EditPostView, add_comment, like_comment, get_comments
)
from .api import PostViewSet, CategoryViewSet, CommentViewSet
from core.urls import router

router.register(r'post_viewset', PostViewSet)
router.register(r'category_viewset', CategoryViewSet)
router.register(r'comment_viewset', CommentViewSet)

app_name = 'blog'

urlpatterns = [
    path('', PostsView.as_view(), name='home'),
    path('post/<slug:slug>/', PostView.as_view(), name='post'),
    path('category/<str:cat>/', CategoryView.as_view(), name='category'),
    path('add_post/', AddPostView.as_view(), name='add_post'),
    path('edit_post/<slug:slug>/', EditPostView.as_view(), name='edit_post'),
    path('add_comment/', add_comment, name='add_comment'),
    path('comment_like/', like_comment, name='like_comment'),
    path('get_comments/<slug:slug>/', get_comments, name='comments'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from rest_framework.routers import DefaultRouter

router = DefaultRouter()

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('blog.urls')),
                  path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
                  path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
                  path('api_auth/', include('rest_framework.urls')),
                  path('auth/', include('account.urls')),
                  path('router/', include(router.urls), name='router'),
              ] + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
) + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

blog/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    title = models.CharField(_("Title"), max_length=128)
    slug = models.SlugField(_("Slug"), db_index=True, unique=True)
    content = models.TextField(_("Content"))
    create_at = models.DateTimeField(_("Create at"), auto_now_add=True)
    update_at = models.DateTimeField(_("Update at"), auto_now=True)
    publish_time = models.DateTimeField(_("Publish at"), db_index=True)
    draft = models.BooleanField(_("Draft"), default=True, db_index=True)
    image = models.ImageField(
        _("image"), upload_to='posts/images/', null=True, blank=True)
    category = models.ForeignKey("Category", verbose_name=_("Category"),
                                 on_delete=models.CASCADE, null=True, blank=True,
                                 related_name='posts', related_query_name='posts')
    author = models.ForeignKey(User, verbose_name=_("Author"), on_delete=models.CASCADE,
                               related_name="posts", related_query_name="children")

    class Meta:
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")
        ordering = ['-publish_time']

    def __str__(self):
        return self.title

    def create_setting(self, comment=True, author=True, allow_discussion=False):
        return PostSetting.objects.create(
            post=self, comment=comment, author=author, allow_discussion=allow_discussion
        )

    def get_comments(self):
        comments = []
        for com in self.comments.filter(parent=None):
            comments.append(
                (com, com.children.all())
            )
        return comments

    @property
    def comment_count(self):
        q = self.comments.all()
        return q.count()

    @property
    def convert_publish_date(self):
        converted_date = f"{self.publish_time.day} - {self.publish_time.month} - {self.publish_time.year}"
        return converted_date

    @property
    def convert_create_date(self):
        converted_date = f"{self.create_at.day} - {self.create_at.month} - {self.create_at.year}"
        return converted_date


class PostSetting(models.Model):
    post = models.OneToOneField(
        "Post", verbose_name=_("post"), on_delete=models.CASCADE,
        related_name='setting', related_query_name='setting')
    comment = models.BooleanField(_("comment"), default=True)
    author = models.BooleanField(_("author"), default=False)
    allow_discussion = models.BooleanField(_("allow discussion"), default=False)

    class Meta:
        verbose_name = _("PostSetting")
        verbose_name_plural = _("PostSettings")


class Category(models.Model):
    title = models.CharField(_("Title"), max_length=50)
    slug = models.SlugField(_("Slug"), unique=True, db_index=True)
    parent = models.ForeignKey("self", verbose_name=_("Parent"), on_delete=models.SET_NULL, null=True, blank=True,
                               related_name='children', related_query_name='children')

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.slug

    def get_children(self):
        return self.children.all()


class CommentLike(models.Model):
    author = models.ForeignKey(User, verbose_name=_(
        "Author"), on_delete=models.CASCADE)
    comment = models.ForeignKey('blog.Comment', verbose_name=_(
        'Comment'), on_delete=models.CASCADE, related_name="comment_like", related_query_name="comment_like")
    condition = models.BooleanField(_("Condition"))
    create_at = models.DateTimeField(_("Create at"), auto_now_add=True)
    update_at = models.DateTimeField(_("Update at"), auto_now=True)

    class Meta:
        unique_together = [['author', 'comment']]
        verbose_name = _("CommentLike")
        verbose_name_plural = _("CommentLikes")

    def __str__(self):
        return str(self.condition)


class Comment(models.Model):
    content = models.TextField(_("Content"))
    post = models.ForeignKey("Post", verbose_name=_("Post"),
                             on_delete=models.CASCADE,
                             related_name='comments', related_query_name='comments')
    create_at = models.DateTimeField(_("Create at"), auto_now_add=True)
    update_at = models.DateTimeField(_("Update at"), auto_now=True)
    author = models.ForeignKey(User, verbose_name=_(
        "Author"), on_delete=models.CASCADE)
    is_confirmed = models.BooleanField(_("confirm"), default=True)
    parent = models.ForeignKey('self', verbose_name=_('parent'), null=True,
                               on_delete=models.CASCADE, blank=True,
                               related_name='children', related_query_name='child')

    class Meta:
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")
        ordering = ['-create_at']

    def __str__(self):
        return self.content[:10]

    @property
    def like_count(self):
        q = CommentLike.objects.filter(comment=self, condition=True)
        return q.count()

    @property
    def dis_like_count(self):
        q = CommentLike.objects.filter(comment=self, condition=False)
        return q.count()

    @property
    def convert_create_date(self):
        converted_date = f"{self.create_at.day} - {self.create_at.month} - {self.create_at.year}"
        return converted_date

blog/models/categroy_comment.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model

User = get_user_model()


class Category(models.Model):
    title = models.CharField(_("Title"), max_length=50)
    slug = models.SlugField(_("Slug"), unique=True, db_index=True)
    parent = models.ForeignKey("self", verbose_name=_("Parent"), on_delete=models.SET_NULL, null=True, blank=True,
                               related_name='children', related_query_name='children')

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.slug


class CommentLike(models.Model):
    author = models.ForeignKey(User, verbose_name=_(
        "Author"), on_delete=models.CASCADE)
    comment = models.ForeignKey('blog.Comment', verbose_name=_(
        'Comment'), on_delete=models.CASCADE, related_name="comment_like", related_query_name="comment_like")
    condition = models.BooleanField(_("Condition"))
    create_at = models.DateTimeField(_("Create at"), auto_now_add=True)
    update_at = models.DateTimeField(_("Update at"), auto_now=True)

    class Meta:
        unique_together = [['author', 'comment']]
        verbose_name = _("CommentLike")
        verbose_name_plural = _("CommentLikes")

    def __str__(self):
        return str(self.condition)


class Comment(models.Model):
    content = models.TextField(_("Content"))
    post = models.ForeignKey("Post", verbose_name=_("Post"),
                             on_delete=models.CASCADE,
                             related_name='comments', related_query_name='comments')
    create_at = models.DateTimeField(_("Create at"), auto_now_add=True)
    update_at = models.DateTimeField(_("Update at"), auto_now=True)
    author = models.ForeignKey(User, verbose_name=_(
        "Author"), on_delete=models.CASCADE)
    is_confirmed = models.BooleanField(_("confirm"), default=True)
    parent = models.ForeignKey('self', verbose_name=_('parent'), null=True,
                               on_delete=models.CASCADE, blank=True,
                               related_name='children', related_query_name='child')

    class Meta:
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")
        ordering = ['-create_at']

    def __str__(self):
        return self.content[:10]

    @property
    def like_count(self):
        q = CommentLike.objects.filter(comment=self, condition=True)
        return q.count()

    @property
    def dis_like_count(self):
        q = CommentLike.objects.filter(comment=self, condition=False)
        return q.count()

blog/forms.py
from django import forms
from .models import Comment, Post
from .validators import slug_validator
from ckeditor.widgets import CKEditorWidget


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'slug', 'category', 'content',
                  'draft', 'publish_time', 'image')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'slug': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'category': forms.Select(attrs={'class': 'form-control mb-3'}),
            'content': CKEditorWidget(),
            'draft': forms.CheckboxInput(attrs={'class': 'form-control mb-3'}),
            'publish_time': forms.SelectDateWidget(attrs={'class': 'form-control mb-3'}),
            'image': forms.FileInput(attrs={'class': 'form-control-file mb-3'}),
        }

    def clean_slug(self):
        slug = self.cleaned_data.get('slug')
        slug_validator(slug)
        return slug


class EditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'category', 'content',
                  'draft', 'publish_time')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'category': forms.Select(attrs={'class': 'form-control mb-3'}),
            'content': forms.Textarea(attrs={'class': 'form-control mb-3', 'cols': 90,
                                             'style': 'resize:none'}),
            'draft': forms.CheckboxInput(attrs={'class': 'form-control mb-3'}),
            'publish_time': forms.SelectDateWidget(attrs={'class': 'form-control mb-3'}),
        }

blog/views.py
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import reverse
from django.views.decorators.csrf import csrf_exempt
from .models import Post, Comment, CommentLike, Category
from .forms import PostForm, EditPostForm
from .mixins import PostAuthorAccessMixin
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from account.mixins import AuthorAccessMixin
from django.db.utils import IntegrityError
import json


class PostsView(ListView):
    model = Post
    paginate_by = 10
    template_name = 'blog/Show/posts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.filter(parent=None)
        return context


class CategoryView(ListView):
    template_name = 'blog/Show/category.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        try:
            cat = Category.objects.get(title=self.kwargs.get('cat'))
            posts = Post.objects.filter(category=cat)
        except Category.DoesNotExist:
            posts = []
        return posts


class PostView(DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'blog/Show/post.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['setting'] = context.get('post').setting
        return context


class AddPostView(AuthorAccessMixin, CreateView):
    model = Post
    template_name = 'blog/Handle/add_post.html'
    form_class = PostForm

    def get_success_url(self):
        return reverse('blog:posts')

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()
        p = Post.objects.get(slug=self.request.POST.get('slug'))
        p.create_setting()
        return HttpResponseRedirect(self.get_success_url())


class EditPostView(AuthorAccessMixin, PostAuthorAccessMixin, UpdateView):
    model = Post
    form_class = EditPostForm
    template_name = 'blog/Handle/edit_post.html'

    def get_success_url(self):
        return reverse('blog:post', kwargs={'slug': self.kwargs.get('slug')})


@csrf_exempt
def get_comments(request, slug):
    comments = Post.objects.get(slug=slug).get_comments()
    comments_dic = list()
    for parent, children in comments:
        children_list = list()
        for child in children:
            children_list.append({'author': child.author.full_name, 'content': child.content,
                                  'create_at': child.create_at, 'like_count': child.like_count,
                                  'dislike_count': child.dis_like_count, 'id': child.id})
        comments_dic.append({'author': parent.author.full_name, 'content': parent.content, 'id': parent.id,
                             'create_at': parent.create_at, 'like_count': parent.like_count,
                             'dislike_count': parent.dis_like_count, 'children': children_list})

    return JsonResponse(comments_dic, safe=False)


@csrf_exempt
def add_comment(request):
    data = json.loads(request.body)
    author = request.user
    if not author.is_authenticated:
        return HttpResponse('No Access', status=403)
    try:
        post = Post.objects.get(slug=data.get('slug'))
    except Post.DoesNotExist:
        return HttpResponse('Bad Request', status=404)
    try:
        parent = Comment.objects.get(pk=data.get('cm_parent'))
        Comment.objects.create(author=author, content=data.get('comment'), post=post, parent=parent)
    except (Comment.DoesNotExist, ValueError):
        Comment.objects.create(author=author, content=data.get('comment'), post=post)
    return HttpResponse('ok')


@csrf_exempt
def like_comment(request):
    data = json.loads(request.body)
    author = request.user
    if not author.is_authenticated:
        return HttpResponse('Not Access', status=403)
    try:
        cm = Comment.objects.get(pk=data.get('comment_id'))
    except Comment.DoesNotExist:
        return HttpResponse('Bad Request', status=404)
    try:
        CommentLike.objects.create(author=author, comment=cm, condition=data.get('condition'))
    except (CommentLike.DoesNotExist, IntegrityError):
        CommentLike.objects.filter(author=author, comment=cm).update(condition=data.get('condition'))

    return HttpResponse('ok')

blog/views/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from blog.models import *
from blog.forms import CommentForm


def home(request):
    return render(request, 'blog/home.html')


def posts(request):
    posts_all = Post.objects.all()
    context = {
        'posts': posts_all,
    }
    return render(request, 'blog/posts.html', context=context)


def post(request, slug):
    # post = get_object_or_404(models.Post)
    post_single = Post.objects.select_related('setting', 'author').get(slug=slug)
    author = User.objects.get(username=request.user.username)
    comments = Comment.objects.filter(post=post_single)
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(data=request.POST)
        form = form.save(commit=False)
        form.post = post_single
        form.author = author
        form.save()
        form = CommentForm()
    context = {
        'post': post_single,
        'setting': post_single.setting,
        'comments': comments,
        'form': form,
    }
    return render(request, 'blog/post.html', context=context)


def category(request):
    catagory_all = Category.objects.all()
    return HttpResponse('')

templates/blog/Show/category.html
{% extends 'base.html' %}
{% block content %}

  <ul class="list-group">
    {% for post in post_list %}
      <li class="list-group-item d-flex align-items-center">
        {% if post.image %}
          <img src="{{ post.image.url }}" alt="" width="30" height="30"
               style="border-radius: 50%; border: 1px solid darkgray; padding: 1px; margin: 0 10px;">
        {% endif %}
        <a class="stretched-link text-info font-weight-bold text-decoration-none"
           href="{% url 'blog:post' post.slug %}">
          <span class="text-primary">
            {{ post }}
          </span>&nbsp;&nbsp;by: {{ post.author|title }}
        </a>
      </li>
    {% endfor %}
  </ul>

  <div class="pagination d-flex justify-content-center my-3">
    <span class="step-links">
        {% if page_obj.has_previous %}
          <a href="?page={{ page_obj.previous_page_number }}"
             class="btn-sm btn-info text-decoration-none">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

      {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}"
           class="btn-sm btn-info text-decoration-none">Next</a>
      {% endif %}
    </span>
  </div>

{% endblock content %}

templates/blog/Show/post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <main class="container my-5">
    <h1 class="h2 my-3 ">{{ post.title }}</h1>
    <span>Author:
        <a class='text-info font-weight-bold text-decoration-none'
           href="">{{ post.author|title }}</a>
    </span>
    <div class="card w-100">
      {% if post.image %}
        <img class="card-img-top" src="{{ post.image.url }}" alt=""
             style="height: 28rem;">
      {% endif %}
      <div class="card-body jumbotron m-0">
        <p class="card-text">{{ post.content|safe }}</p>
      </div>
    </div>
    <div class=" mb-5  d-flex justify-content-between text-primary">
      <span>
        Show Author: <span class="font-weight-bold">{{ setting.author }}</span>,&nbsp;
        Show Comment: <span class="font-weight-bold">{{ setting.comment }}</span>,&nbsp;
        Allow Discussions: <span class="font-weight-bold">
                            {{ setting.allow_discussion }}</span>,
      </span>
    </div>
    <hr>
    <div class="d-flex align-items-center flex-column" id="comments"></div>
    <hr>
    <div class="d-flex flex-column align-items-center" id="commentFrom">
      {% if user.is_authenticated %}
        <div class="d-flex justify-content-start w-75">
          <label for="addComment" id="contentLabel">Content:</label>
        </div>
        <input type="hidden" value="" id="cmParent">
        <textarea name="comment" id="addComment" cols="30" rows="10"
                  class="form-control d-block w-75" style="resize: none;"></textarea>
        <div class="d-flex justify-content-end w-75">
          <button class="btn btn-outline-primary my-2 d-block float-left"
                  onclick="sendComment('{{ post.slug }}')">
            Send comment
          </button>
        </div>
      {% endif %}
    </div>
  </main>

{% endblock content %}

{% block javascript %}
  <script src="{% static 'jquery/jquery.js' %}"></script>
  <script src="{% static 'jquery/blog.js' %}"></script>
  <script>
      getComments('{% url 'blog:comments' post.slug %}');
  </script>
{% endblock javascript %}

templates/blog/Show/posts.html
{% extends 'base.html' %}
{% block content %}

    <main class="row m-0">
        <section class="col-9">
            <ul class="list-group">
                {% for post in post_list %}
                    <li class="list-group-item d-flex align-items-center my-1">
                        {% if post.image %}
                            <img src="{{ post.image.url }}" alt="" width="30" height="30"
                                 style="border-radius: 50%; border: 1px solid darkgray; padding: 1px; margin: 0 10px;">
                        {% endif %}
                        <a class="stretched-link text-info font-weight-bold text-decoration-none"
                           href="{% url 'blog:post' post.slug %}">
                          <span class="text-primary">
                            {{ post }}
                          </span>&nbsp;&nbsp;by: {{ post.author|title }}
                        </a>
                    </li>
                {% endfor %}
            </ul>

            <div class="pagination d-flex justify-content-center my-3">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}"
               class="btn-sm btn-info text-decoration-none">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}"
               class="btn-sm btn-info text-decoration-none">Next</a>
        {% endif %}
    </span>
            </div>
        </section>
        <section class="col-3 w-100">
            <aside class="my-2 border-left">
                <ul class="list-group my-2">
                    {% for cat in category %}
                        <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-info">
                            <a class="stretched-link text-decoration-none"
                               href="{% url 'blog:category' cat %}">{{ cat|title }}</a>
                            <span class="badge badge-primary badge-pill">{{ cat.posts.count }}</span>
                        </li>
                        <ul class="list-group pl-4">
                            {% for child in cat.get_children %}
                                {% if forloop.last %}
                                    <li class="list-group-item d-flex justify-content-between align-items-center border-0">
                                        {% else %}
                                    <li class="list-group-item d-flex justify-content-between align-items-center border-0"
                                        style="border-bottom: 1px solid #cbcbcb !important;">
                                {% endif %}
                            <a class="stretched-link text-decoration-none"
                               href="{% url 'blog:category' cat %}">{{ child|title }}</a>
                            <span class=" badge badge-primary badge-pill">{{ child.posts.count }}</span>
                            </li>
                            {% endfor %}
                        </ul>
                    {% endfor %}
                </ul>
            </aside>
        </section>
    </main>

{% endblock content %}