account/urls.py
from django.urls import path
from .views import SingInView, SignUpView, SignOutView, ProfileView, activate
from core.urls import router
from .api import UserViewSet

router.register(r'users', UserViewSet)

app_name = 'account'

urlpatterns = [
    path('login/', SingInView.as_view(), name='login'),
    path('logout/', SignOutView.as_view(), name='logout'),
    path('register/', SignUpView.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('profile/', ProfileView.as_view(), name='profile')
]

blog/urls.py
from django.urls import path
from blog.views import (
    PostView, PostsView, CategoryView,
    AddPostView, EditPostView, add_comment, like_comment, get_comments
)
from .api import PostViewSet, CategoryViewSet, CommentViewSet
from core.urls import router

router.register(r'post_viewset', PostViewSet)
router.register(r'category_viewset', CategoryViewSet)
router.register(r'comment_viewset', CommentViewSet)

app_name = 'blog'

urlpatterns = [
    path('', PostsView.as_view(), name='home'),
    path('post/<slug:slug>/', PostView.as_view(), name='post'),
    path('category/<str:cat>/', CategoryView.as_view(), name='category'),
    path('add_post/', AddPostView.as_view(), name='add_post'),
    path('edit_post/<slug:slug>/', EditPostView.as_view(), name='edit_post'),
    path('add_comment/', add_comment, name='add_comment'),
    path('comment_like/', like_comment, name='like_comment'),
    path('get_comments/<slug:slug>/', get_comments, name='comments'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from rest_framework.routers import DefaultRouter

router = DefaultRouter()

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('blog.urls')),
                  path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
                  path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
                  path('api_auth/', include('rest_framework.urls')),
                  path('auth/', include('account.urls')),
                  path('router/', include(router.urls), name='router'),
              ] + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
) + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

templates/base.html
{% load static %}
{% load permission %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'css/bootstrap.style.css' %}">
  <link rel="stylesheet" href="{% static 'css/my_style.css' %}">
  <title>Blog</title>
  {% block extra_link %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand navbar-dark bg-dark">
  <div class="w-100 d-flex ">
    <a class="navbar-brand">Blog</a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:home' %}">Home</a>
      </li>
      {% if user.is_authenticated %}
        {% if user|is_author or user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account:profile' %}">Profile</a>
          </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="">{{ user.full_name|title }}</a>
        </li>
        <div class="text-secondary h2">/</div>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account:login' %}">Login</a>
        </li>
        <div class="text-secondary h2">/</div>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account:register' %}">Register</a>
        </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
{% block content %} {% endblock content %}
<script src="{% static 'bootstrap.jquery.js' %}"></script>
<script src="{% static 'bootstrap.js' %}"></script>
{% block javascript %} {% endblock javascript %}
</body>
</html>